create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  title text not null,
  department text,
  status text default 'active',
  user_id uuid,
  created_at timestamptz default now()
);