create table tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    completed boolean not null default false
);

insert into tasks (title, completed)
values
    ('Aprender FastAPI', false),
    ('Conectar Vue', false),
    ('Conectar Supabase', false);